/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.rummikiub.ventanas;

import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;

import javax.swing.JFrame;

/**
 *
 * @author barra
 */
public class ChatPanel extends javax.swing.JPanel {
    Socket socket;
    JFrame parent;
    /**
     * Creates new form Chat
     */
    public ChatPanel(Socket socket, JFrame parent) {
        this.socket = socket;
        this.parent = parent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblChat = new javax.swing.JLabel();
        scpChatContainer = new javax.swing.JScrollPane();
        txaChat = new javax.swing.JTextArea();
        txfChat = new javax.swing.JTextField();
        btnEnviarChat = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255, 0));
        setForeground(new java.awt.Color(255, 255, 255));
        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblChat.setBackground(new java.awt.Color(255, 255, 255));
        lblChat.setForeground(new java.awt.Color(255, 255, 255));
        lblChat.setText("Chat:");
        add(lblChat, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        scpChatContainer.setBackground(new java.awt.Color(255, 255, 255, 0));
        scpChatContainer.setOpaque(false);
        scpChatContainer.getViewport().setOpaque(false);

        txaChat.setBackground(new java.awt.Color(255, 255, 255, 0));
        txaChat.setColumns(20);
        txaChat.setForeground(new java.awt.Color(255, 255, 255));
        txaChat.setRows(5);
        txaChat.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txaChat.setOpaque(false);
        txaChat.setEnabled(false);
        scpChatContainer.setViewportView(txaChat);

        add(scpChatContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 950, 110));

        txfChat.setBackground(new java.awt.Color(255, 255, 255, 0));
        txfChat.setOpaque(false);
        txfChat.setForeground(new java.awt.Color(255, 255, 255));
        add(txfChat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 810, 30));

        btnEnviarChat.setBackground(new java.awt.Color(51, 51, 51));
        btnEnviarChat.setForeground(new java.awt.Color(255, 255, 255));
        btnEnviarChat.setText("Enviar");
        btnEnviarChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarChatActionPerformed(evt);
            }
        });
        add(btnEnviarChat, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 150, 130, -1));
    }// </editor-fold>//GEN-END:initComponents

    public void disableChat(){
        txfChat.setEnabled(false);
        txaChat.setEnabled(false);
        btnEnviarChat.setEnabled(false);
    }

    public void enableChat(){
        txfChat.setEnabled(true);
        btnEnviarChat.setEnabled(true);
    }

    private String getChatMessage(){
        return txfChat.getText();
    }

    public void chat_in(String mensaje, String autor){
        txaChat.append(autor + ": " + mensaje + "\n");
    }

    private void btnEnviarChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarChatActionPerformed
        String mensaje = getChatMessage();
        String autor;
        if (parent instanceof HomeWindow) autor = ((HomeWindow) parent).getUsername();
        else if (parent instanceof LobbyWindow) autor = ((LobbyWindow) parent).getUsername();
        else autor = "PENDING";
        if(mensaje.length() > 0){
            DataOutputStream salida = null;
            try {
                salida = new DataOutputStream(socket.getOutputStream());
                salida.writeInt(0002);
                salida.writeUTF(mensaje);
                salida.writeUTF(autor);
            } catch (IOException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }
        }
        txfChat.setText("");
    }//GEN-LAST:event_btnEnviarChatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviarChat;
    private javax.swing.JLabel lblChat;
    private javax.swing.JScrollPane scpChatContainer;
    private javax.swing.JTextArea txaChat;
    private javax.swing.JTextField txfChat;
    // End of variables declaration//GEN-END:variables
}
