/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.rummikiub.ventanas;

import java.net.Socket;

/**
 *
 * @author barra
 */
public class ChatPanel extends javax.swing.JPanel {
    Socket socket;
    /**
     * Creates new form Chat
     */
    public ChatPanel(Socket socket) {
        this.socket = socket;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblChat = new javax.swing.JLabel();
        scpChatContainer = new javax.swing.JScrollPane();
        txaChat = new javax.swing.JTextArea();
        txfChat = new javax.swing.JTextField();
        btnEnviarChat = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255, 0));
        setForeground(new java.awt.Color(255, 255, 255));
        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblChat.setBackground(new java.awt.Color(255, 255, 255));
        lblChat.setForeground(new java.awt.Color(255, 255, 255));
        lblChat.setText("Chat:");
        add(lblChat, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        scpChatContainer.setBackground(new java.awt.Color(255, 255, 255, 0));
        scpChatContainer.setOpaque(false);
        scpChatContainer.getViewport().setOpaque(false);

        txaChat.setBackground(new java.awt.Color(255, 255, 255, 0));
        txaChat.setColumns(20);
        txaChat.setForeground(new java.awt.Color(255, 255, 255));
        txaChat.setRows(5);
        txaChat.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txaChat.setOpaque(false);
        scpChatContainer.setViewportView(txaChat);

        add(scpChatContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 950, 110));

        txfChat.setBackground(new java.awt.Color(255, 255, 255, 0));
        txfChat.setOpaque(false);
        txfChat.setForeground(new java.awt.Color(255, 255, 255));
        add(txfChat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 810, 30));

        btnEnviarChat.setBackground(new java.awt.Color(51, 51, 51));
        btnEnviarChat.setForeground(new java.awt.Color(255, 255, 255));
        btnEnviarChat.setText("Enviar");
        add(btnEnviarChat, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 150, 130, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviarChat;
    private javax.swing.JLabel lblChat;
    private javax.swing.JScrollPane scpChatContainer;
    private javax.swing.JTextArea txaChat;
    private javax.swing.JTextField txfChat;
    // End of variables declaration//GEN-END:variables
}
