/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.rummikiub.ventanas;

import java.io.DataOutputStream;
import java.io.IOException;
import java.io.DataOutputStream;
import java.net.Socket;

import javax.swing.JOptionPane;

import com.mycompany.rummikiub.Cliente;

/**
 *
 * @author barra
 */
public class CrearPartidaPopUp extends javax.swing.JFrame {
    private Socket socket;
    private String username;
    private Cliente cliente;

    /**
     * Creates new form CrearPartidaPopUp
     */
    public CrearPartidaPopUp(Socket socket, String username, Cliente cliente) {
        this.socket = socket;
        this.username = username;
        this.cliente = cliente;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCantidadJugadores = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        cbxCantidadJugadores = new javax.swing.JComboBox<>();
        lblNombrePartida = new javax.swing.JLabel();
        btnCrearPartida = new javax.swing.JButton();
        txfNombrePartida = new javax.swing.JTextField();
        bgImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Crear partida");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCantidadJugadores.setBackground(new java.awt.Color(255, 255, 255));
        lblCantidadJugadores.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCantidadJugadores.setForeground(new java.awt.Color(255, 255, 255));
        lblCantidadJugadores.setText("Jugadores;");
        getContentPane().add(lblCantidadJugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        lblTitulo.setBackground(new java.awt.Color(255, 255, 255));
        lblTitulo.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 48)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Crear partida");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        cbxCantidadJugadores.setBackground(new java.awt.Color(51, 51, 51));
        cbxCantidadJugadores.setForeground(new java.awt.Color(255, 255, 255));
        cbxCantidadJugadores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4" }));
        cbxCantidadJugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCantidadJugadoresActionPerformed(evt);
            }
        });
        getContentPane().add(cbxCantidadJugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        lblNombrePartida.setBackground(new java.awt.Color(255, 255, 255));
        lblNombrePartida.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNombrePartida.setForeground(new java.awt.Color(255, 255, 255));
        lblNombrePartida.setText("Nombre partida:");
        getContentPane().add(lblNombrePartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        btnCrearPartida.setBackground(new java.awt.Color(51, 51, 51));
        btnCrearPartida.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearPartida.setText("Crear partida");
        btnCrearPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearPartidaActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrearPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        txfNombrePartida.setBackground(new java.awt.Color(255, 255, 255, 0));
        txfNombrePartida.setOpaque(false);
        txfNombrePartida.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txfNombrePartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 160, -1));

        bgImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/rummikiub/assets/backgroundPopUp.jpg"))); // NOI18N
        getContentPane().add(bgImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxCantidadJugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCantidadJugadoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxCantidadJugadoresActionPerformed

    private void btnCrearPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearPartidaActionPerformed
        if (txfNombrePartida.getText().length() < 1){
            JOptionPane.showMessageDialog(this, "El nombre de partida no puede estar vacía");
            return;
        }
        String nombrePartida = txfNombrePartida.getText();
        int cantidadJugadores = Integer.parseInt(cbxCantidadJugadores.getSelectedItem().toString());
        DataOutputStream salida = null;
        try {
            salida = new DataOutputStream(socket.getOutputStream());
            salida.writeInt(0004);
            salida.writeUTF(nombrePartida);
            salida.writeInt(cantidadJugadores);
        } catch (IOException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        
        this.dispose();
    }//GEN-LAST:event_btnCrearPartidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearPartidaPopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearPartidaPopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearPartidaPopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearPartidaPopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearPartidaPopUp(null, "", null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgImage;
    private javax.swing.JButton btnCrearPartida;
    private javax.swing.JComboBox<String> cbxCantidadJugadores;
    private javax.swing.JLabel lblCantidadJugadores;
    private javax.swing.JLabel lblNombrePartida;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txfNombrePartida;
    // End of variables declaration//GEN-END:variables
}
