/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.rummikiub.ventanas;

import java.net.Socket;
import java.util.ArrayList;

import com.mycompany.rummikiub.Cliente;
import com.mycompany.rummikiub.Partida;

/**
 *
 * @author barra
 */
public class GameGUI extends javax.swing.JFrame {
    private Socket cliente;
    private Cliente clienteApp;
    private String username;
    private int cantidadJugadores;
    private ArrayList<String> jugadores;
    private String matrizJuego[][] = new String[6][18];
    private ArrayList<String> mazoJugador = new ArrayList<String>();
    private Ficha currentFicha = null;
    private boolean currentFichaPos = false;

    /**
     * Creates new form testing
     */
    public GameGUI() {
        for (int i = 0; i < 6; i++){
            for (int j = 0; j < 18; j++){
                matrizJuego[i][j] = "T";
            }
        }
        jugadores = new ArrayList<String>();
        jugadores.add("Jugador 1");
        jugadores.add("Jugador 2");
        username = "Jugador 2";
        cantidadJugadores = 2;
        initComponents();
    }

    public GameGUI(Socket cliente, Cliente clienteApp, String username, int cantidadJugadores, ArrayList<String> jugadores, ArrayList<String> mazoJugador) {
        this.cliente = cliente;
        this.clienteApp = clienteApp;
        this.username = username;
        this.cantidadJugadores = cantidadJugadores;
        this.jugadores = jugadores;
        this.mazoJugador = mazoJugador;
        for (int i = 0; i < 6; i++){
            for (int j = 0; j < 18; j++){
                matrizJuego[i][j] = "T";
            }
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gameGrid2 = new com.mycompany.rummikiub.ventanas.GameGrid(matrizJuego, this);
        mazoJugador2 = new com.mycompany.rummikiub.ventanas.MazoJugador();
        userCircle1 = new com.mycompany.rummikiub.ventanas.UserCircle();
        userCircle2 = new com.mycompany.rummikiub.ventanas.UserCircle();
        userCircle3 = new com.mycompany.rummikiub.ventanas.UserCircle();
        btnTerminarTurno = new javax.swing.JButton();
        lblStand = new javax.swing.JLabel();
        bgImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gameGrid2.setBackground(new java.awt.Color(0, 0, 0, 0));
        gameGrid2.setOpaque(false);
        getContentPane().add(gameGrid2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 770, 520));

        mazoJugador2.setBackground(new java.awt.Color(0, 0, 0, 0));
        mazoJugador2.setOpaque(false);
        getContentPane().add(mazoJugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 1220, 180));
        for(int i = 0; i < mazoJugador.size(); i++){
            mazoJugador2.addFicha(mazoJugador.get(i));
            mazoJugador2.getFichas().get(i).addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    currentFicha = (Ficha) evt.getSource();
                    currentFichaPos = false;
                    System.out.println("Ficha clickeada " + currentFicha.getColor());
                }
            });
        }

        UserCircle userCircles[] = {userCircle1, userCircle2, userCircle3};
        for (int i = 0; i < cantidadJugadores; i++){
            if (!(jugadores.get(i).equals(username))){
                userCircles[i].setNombre(jugadores.get(i));
                userCircles[i].setCantidadFichas(14);
                userCircles[i].setMarco(false);
                userCircles[i].setBackground(new java.awt.Color(0, 0, 0, 0));
                userCircles[i].setOpaque(false);
                getContentPane().add(userCircles[i], new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20 + 160 * i, 100, 130));
            }
        }

        btnTerminarTurno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/rummikiub/assets/TerminarTurno.png"))); // NOI18N
        btnTerminarTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerminarTurnoActionPerformed(evt);
            }
        });
        getContentPane().add(btnTerminarTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 200, 140, 210));

        lblStand.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/rummikiub/assets/standMadera.png"))); // NOI18N
        getContentPane().add(lblStand, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 1220, 200));

        bgImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/rummikiub/assets/gameBackground.jpg"))); // NOI18N
        getContentPane().add(bgImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTerminarTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerminarTurnoActionPerformed
        clienteApp.sendInt(1);
    }//GEN-LAST:event_btnTerminarTurnoActionPerformed

    public void registerMove(String codigoFicha, String pos1, String pos2, String comodin){
        int i1 = Integer.parseInt(pos1.split(" ")[0]);
        int j1 = Integer.parseInt(pos1.split(" ")[1]);
        int i2 = Integer.parseInt(pos2.split(" ")[0]);
        int j2 = Integer.parseInt(pos2.split(" ")[1]);
        Ficha ficha1;
        if (codigoFicha.length() < 5 || codigoFicha.length() > 6){
            if(codigoFicha.equals("como")) ficha1 = new Ficha(0, "comodin", true, 0, i1, j1);
            else if (codigoFicha.length() > 7 && codigoFicha.contains("table")) ficha1 = new Ficha(-1, "tablero", false, 0, i1, j1);
            else ficha1 = new Ficha(Integer.parseInt(codigoFicha.substring(4)), codigoFicha.substring(0, 4), false, 0, i1, j1);
        }
        else if (i1 == -1) ficha1 = new Ficha(Integer.parseInt(codigoFicha.substring(4)), codigoFicha.substring(0, 4), comodin.equals("1"), 0, i1, j1);
        else ficha1 = gameGrid2.getFichas()[i1][j1];
        Ficha ficha2 = gameGrid2.getFichas()[i2][j2];
        Ficha temp = new Ficha();
        temp.morph(ficha1);
        ficha1.morph(ficha2);
        ficha2.morph(temp);
        if (i1 == -1) remove(ficha2);
        else gameGrid2.getFichas()[i1][j1] = ficha2;
        gameGrid2.getFichas()[i2][j2] = ficha1;
        gameGrid2.revalidate();
    }

    public void removeFicha(){
        try {
            mazoJugador2.remove(currentFicha);
            mazoJugador2.revalidate();
        } catch (Exception e) {
            // TODO: handle exception
        }
    }

    public Ficha getCurrentFicha(){
        return currentFicha;
    }

    public void setCurrentFicha(Ficha ficha){
        currentFicha = ficha;
    }

    public boolean getCurrentFichaPos(){
        return currentFichaPos;
    }

    public void setCurrentFichaPos(boolean pos){
        currentFichaPos = pos;
    }

    public Cliente getClienteApp(){
        return clienteApp;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgImage;
    private javax.swing.JButton btnTerminarTurno;
    private com.mycompany.rummikiub.ventanas.GameGrid gameGrid2;
    private javax.swing.JLabel lblStand;
    private com.mycompany.rummikiub.ventanas.MazoJugador mazoJugador2;
    private com.mycompany.rummikiub.ventanas.UserCircle userCircle1;
    private com.mycompany.rummikiub.ventanas.UserCircle userCircle2;
    private com.mycompany.rummikiub.ventanas.UserCircle userCircle3;
    // End of variables declaration//GEN-END:variables
}
