/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.rummikiub.ventanas;

/**
 *
 * @author barra
 */
public class gameGrid extends javax.swing.JPanel {
    private Ficha[][] fichas  = new Ficha[6][18];
    /**
     * Creates new form gameGrid
     */
    public gameGrid() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        createGrid();
        setLayout(new java.awt.GridLayout(6, 18));
    }// </editor-fold>//GEN-END:initComponents
    
    public void createGrid(){
        for (int i = 0; i < 6; i++){
            for (int j = 0; j < 18; j++){
                fichas[i][j] = new Ficha(-1, "", false, 0);
                this.add(fichas[i][j]);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
