/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.rummikiub.ventanas;

import java.util.ArrayList;

/**
 *
 * @author barra
 */
public class MazoJugador extends javax.swing.JPanel {
    int i = 0;
    ArrayList<Ficha> fichas = new ArrayList<Ficha>();
    /**
     * Creates new form MazoJugador
     */
    public MazoJugador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridLayout(2, 10));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Ficha ficha = new Ficha(++i, "rojo", false, 0);
        ficha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                System.out.println("Ficha clickeada " + ficha.getColor());
            }
        });
        // i++;
        this.add(ficha);
        this.revalidate();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void addFicha(String codigoFicha){
        Ficha ficha = new Ficha(Integer.parseInt(codigoFicha.substring(4)), codigoFicha.substring(0, 4), false, 0);
        fichas.add(ficha);
        this.add(ficha);
        this.revalidate();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
