/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.rummikiub.ventanas;

import java.util.ArrayList;

import javax.swing.JOptionPane;

import com.mycompany.rummikiub.Cliente;
import com.mycompany.rummikiub.ClienteSocketThread;

/**
 *
 * @author barra
 */
public class PartidasDisponibles extends javax.swing.JFrame {
    private ArrayList<String[]> partidas;
    private Cliente cliente;
    /**
     * Creates new form PartidasDisponibles
     */
    public PartidasDisponibles(ArrayList<String[]> partidas, Cliente cliente) {
        this.partidas = partidas;
        this.cliente = cliente;
        initComponents();
        fillComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        cbxPartidasDisponibles = new javax.swing.JComboBox<>();
        btnEntrarPartida = new javax.swing.JButton();
        bgImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setBackground(new java.awt.Color(255, 255, 255));
        lblTitulo.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 48)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Partidas disponibles");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        cbxPartidasDisponibles.setBackground(new java.awt.Color(51, 51, 51));
        cbxPartidasDisponibles.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(cbxPartidasDisponibles, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 350, 50));

        btnEntrarPartida.setBackground(new java.awt.Color(51, 51, 51));
        btnEntrarPartida.setForeground(new java.awt.Color(255, 255, 255));
        btnEntrarPartida.setText("Elegir partida");
        btnEntrarPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarPartidaActionPerformed(evt);
            }
        });
        getContentPane().add(btnEntrarPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 180, 40));

        bgImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/rummikiub/assets/backgroundPopUp.jpg"))); // NOI18N
        getContentPane().add(bgImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fillComboBox(){
        ArrayList<String> partidasDisponibles = new ArrayList<String>();
        for (String[] partida : partidas) {
            partidasDisponibles.add(partida[1] + " de " + partida[0] + " con " + partida[2] + "/" + partida[3] + " jugadores");
        }
        cbxPartidasDisponibles.setModel(new javax.swing.DefaultComboBoxModel<>(partidasDisponibles.toArray(new String[partidasDisponibles.size()])));
    }

    private void btnEntrarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarPartidaActionPerformed
        String partidaIndex = cbxPartidasDisponibles.getSelectedIndex() + "";
        int index = Integer.parseInt(partidaIndex);
        if (index == -1)
            return;
        if (partidas.get(index)[2].equals(partidas.get(index)[3])){
            JOptionPane.showMessageDialog(this, "Sala llena");
            return;
        }
        System.out.println(partidaIndex);
        cliente.sendInt(8);
        cliente.sendUTF(partidaIndex);
        dispose();
    }//GEN-LAST:event_btnEntrarPartidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PartidasDisponibles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PartidasDisponibles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PartidasDisponibles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PartidasDisponibles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PartidasDisponibles(null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgImage;
    private javax.swing.JButton btnEntrarPartida;
    private javax.swing.JComboBox<String> cbxPartidasDisponibles;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
